USE RESTAURANT_ANALYTICS_DB;
USE SCHEMA CLEANED;

CREATE OR REPLACE TABLE CLEANED.CLEANED_CUSTOMERS (
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    LOYALTY_TIER STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    UPDATED_AT STRING,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

SELECT * FROM CLEANED.CLEANED_CUSTOMERS;

INSERT INTO CLEANED.CLEANED_CUSTOMERS
VALUES
(
    'CU1001',
    'Prajakta',
    'Das',
    'prajakta.das1@mail.com',
    9110000001,
    'PREMIUM',
    'Noida',
    'UP',
    'India',
    '08/31/2025 21:12',
    CURRENT_TIMESTAMP(),
    'Manual Insert'
);

DELETE FROM  CLEANED.CLEANED_CUSTOMERS WHERE EMAIL = 'prajakta.das1@mail.com';

UPDATE CLEANED.CLEANED_CUSTOMERS
SET LOYALTY_TIER = 'VIP'
WHERE EMAIL = 'prajakta.das1@mail.com';

SELECT * FROM CLEANED.CLEANED_CUSTOMERS;
TRUNCATE TABLE CLEANED.CLEANED_CUSTOMERS;

CREATE OR REPLACE TABLE CLEANED.CLEANED_ORDERS (
    ORDER_ID STRING,
    ORDER_LINE_ID STRING,
    ORDER_DATE STRING,
    CUSTOMER_ID STRING,
    MENU_ITEM_ID STRING,
    RESTAURANT_ID STRING,
    ORDER_CHANNEL STRING,
    QTY STRING,
    UNIT_PRICE STRING,
    DISCOUNT_PCT STRING,
    PAYMENT_TYPE STRING,
    ORDER_STATUS STRING,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

SELECT * FROM CLEANED.CLEANED_ORDERS;
TRUNCATE TABLE CLEANED.CLEANED_ORDERS; 

CREATE OR REPLACE TABLE CLEANED.CLEANED_MENU_ITEMS (
    MENU_ITEM_ID STRING,
    ITEM_NAME STRING,
    TYPE STRING,
    CUISINE STRING,
    DIET_TYPE STRING,
    LIST_PRICE STRING,
    STATUS STRING,
    UPDATED_AT STRING,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

SELECT * FROM CLEANED.CLEANED_MENU_ITEMS;

INSERT INTO CLEANED.CLEANED_MENU_ITEMS
VALUES
(
  'M1101',
  'Sushi',
  'Main Course',
  'Japanese',
  'Non-Veg',
  '350',
  'ACTIVE',
  '12-09-2025 19:30',
  CURRENT_TIMESTAMP(),
  'Manual Insert'
);

UPDATE CLEANED.CLEANED_MENU_ITEMS SET CUISINE = 'Indian' WHERE MENU_ITEM_ID = 'M1101';

SELECT * FROM CLEANED.CLEANED_MENU_ITEMS;
TRUNCATE TABLE CLEANED.CLEANED_MENU_ITEMS;

CREATE OR REPLACE TABLE CLEANED.CLEANED_RESTAURANTS (
    RESTAURANT_ID STRING,
    NAME STRING,
    REGION STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    OPEN_DATE STRING,
    SERVICE_MODES STRING,
    STATUS STRING,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

SELECT * FROM CLEANED.CLEANED_RESTAURANTS;

INSERT INTO CLEANED.CLEANED_RESTAURANTS
VALUES
(
  '0000098',
  'Test Bistro – New',
  'SOUTH',
  'Chennai',
  'TN',
  'India',
  DATE '2026-02-05',
  'DINE_IN,DELIVERY',
  'OPEN',
  CURRENT_TIMESTAMP(),
  'Manual Insert'
);

SELECT * FROM CLEANED.CLEANED_RESTAURANTS;
DELETE FROM CLEANED.CLEANED_RESTAURANTS WHERE RESTAURANT_NAME = 'Roadside Bistro – Mumbai';

UPDATE CLEANED.CLEANED_RESTAURANTS SET CITY = 'Bengaluru' WHERE RESTAURANT_ID = 'R001';

TRUNCATE TABLE CLEANED.CLEANED_RESTAURANTS;



ALTER ACCOUNT SET ENABLE_ACCOUNT_REPLICATION = TRUE;