USE DATABASE RESTAURANT_ANALYTICS_DB;
USE SCHEMA DW;

CREATE OR REPLACE TABLE DW.DIM_CUSTOMER (
    SK_CUSTOMER INT PRIMARY KEY,

    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    LOYALTY_TIER STRING,
    CITY STRING,
    STATE STRING,

    EFF_START_TS TIMESTAMP,
    EFF_END_TS TIMESTAMP,
    IS_CURRENT BOOLEAN,

    LOAD_TS TIMESTAMP
);

SELECT * FROM DW.DIM_CUSTOMER;
DELETE FROM DW.DIM_CUSTOMER WHERE CUSTOMER_ID = 'CU1001';

TRUNCATE TABLE DW.DIM_CUSTOMER;


CREATE OR REPLACE TABLE DW.DIM_MENU_ITEM (
    SK_MENU_ITEM INT PRIMARY KEY,        -- Surrogate key from IDMC sequence

    MENU_ITEM_ID STRING,                 -- Business key
    ITEM_NAME STRING,
    TYPE STRING,
    CUISINE STRING,
    DIET_TYPE STRING,

    LIST_PRICE STRING,             -- Converted from string in CLEANED
    STATUS STRING,                       -- or BOOLEAN if you standardize later
    UPDATED_AT STRING,                -- last update from source

    -- SCD TYPE 2 COLUMNS
    EFF_START_TS TIMESTAMP,
    EFF_END_TS TIMESTAMP,
    IS_CURRENT BOOLEAN,

    LOAD_TS TIMESTAMP
);

SELECT * FROM DW.DIM_MENU_ITEM;
TRUNCATE TABLE DW.DIM_MENU_ITEM;

CREATE OR REPLACE TABLE DW.DIM_RESTAURANT (
  SK_RESTAURANT NUMBER  PRIMARY KEY,
  RESTAURANT_ID STRING,
  RESTAURANT_NAME STRING,
  REGION STRING,
  CITY STRING,
  STATE STRING,
  COUNTRY STRING,
  SERVICE_MODES STRING,
  STATUS STRING,
  LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

SELECT * FROM DW.DIM_RESTAURANT;
TRUNCATE TABLE DW.DIM_RESTAURANT;


DELETE FROM DW.DIM_RESTAURANT WHERE RESTAURANT_NAME='Roadside Bistro – Uttarakhand';

CREATE OR REPLACE TABLE DW.DIM_DATE (
    SK_DATE        NUMBER ,
    DATE_VALUE     DATE,
    YEAR           NUMBER,
    MONTH          NUMBER,
    QUARTER        NUMBER,
    WEEK_OF_YEAR   NUMBER,
    IS_WEEKEND     NUMBER
);

SELECT * FROM DW.DIM_DATE;

TRUNCATE TABLE DW.DIM_DATE;

CREATE OR REPLACE TABLE DW.FACT_ORDERS (
    -- Primary Key (order line grain)
    ORDER_ID        STRING,
    ORDER_LINE_ID   STRING,

    -- Foreign Keys
    SK_DATE         NUMBER,   -- FK to DIM_DATE
    SK_CUSTOMER     NUMBER,   -- FK to DIM_CUSTOMER (SCD2)
    SK_MENU_ITEM    NUMBER,   -- FK to DIM_MENU_ITEM (SCD2)
    SK_RESTAURANT   NUMBER,   -- FK to DIM_RESTAURANT (Type 1)

    -- Measures
    QTY             NUMBER,
    UNIT_PRICE      NUMBER(10,2),
    DISCOUNT_PCT    NUMBER(10,2),
    NET_AMOUNT      NUMBER(10,2),

    -- Order attributes
    ORDER_CHANNEL         STRING,
    PAYMENT_TYPE  STRING,


    PRIMARY KEY (ORDER_ID, ORDER_LINE_ID)
);

SELECT * FROM DW.FACT_ORDERS;
TRUNCATE TABLE DW.FACT_ORDERS;