USE RESTAURANT_ANALYTICS_DB;
CREATE OR REPLACE SCHEMA SEMANTIC;

USE DATABASE RESTAURANT_ANALYTICS_DB;
USE SCHEMA SEMANTIC;

CREATE OR REPLACE DYNAMIC TABLE SEMANTIC.DT_ORDER_ANALYTICS
  TARGET_LAG = '1 hour'
  WAREHOUSE  = COMPUTE_WH
AS
SELECT
    /* Fact grain keys */
    f.ORDER_ID,
    f.ORDER_LINE_ID,

    /* Date dimension */
    d.SK_DATE,
    d.DATE_VALUE,
    d.YEAR,
    d.MONTH,
    d.QUARTER,
    d.WEEK_OF_YEAR,
    d.IS_WEEKEND,

    /* Restaurant dimension */
    r.SK_RESTAURANT,
    r.RESTAURANT_ID,
    r.RESTAURANT_NAME,
    r.REGION,
    r.CITY            AS RESTAURANT_CITY,
    r.STATE           AS RESTAURANT_STATE,
    r.COUNTRY,
    r.SERVICE_MODES,
    r.STATUS          AS RESTAURANT_STATUS,

    /* Customer dimension (SCD2 current) */
    c.SK_CUSTOMER,
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.EMAIL,
    c.PHONE,
    c.LOYALTY_TIER,
    c.CITY            AS CUSTOMER_CITY,
    c.STATE           AS CUSTOMER_STATE,

    /* Menu item dimension (SCD2 current) */
    m.SK_MENU_ITEM,
    m.MENU_ITEM_ID,
    m.ITEM_NAME,
    m.TYPE            AS ITEM_TYPE,
    m.CUISINE,
    m.DIET_TYPE,
    TRY_TO_NUMBER(m.LIST_PRICE) AS LIST_PRICE_NUM,
    m.STATUS          AS MENU_ITEM_STATUS,
    m.UPDATED_AT      AS MENU_ITEM_UPDATED_AT,

    /* Measures */
    f.QTY,
    f.UNIT_PRICE,
    f.DISCOUNT_PCT,
    f.NET_AMOUNT,

    /* Order attributes */
    f.ORDER_CHANNEL,
    f.PAYMENT_TYPE

FROM DW.FACT_ORDERS f
LEFT JOIN DW.DIM_DATE d
       ON f.SK_DATE = d.SK_DATE
LEFT JOIN DW.DIM_RESTAURANT r
       ON f.SK_RESTAURANT = r.SK_RESTAURANT
LEFT JOIN DW.DIM_CUSTOMER c
       ON f.SK_CUSTOMER = c.SK_CUSTOMER
      AND c.IS_CURRENT = TRUE
LEFT JOIN DW.DIM_MENU_ITEM m
       ON f.SK_MENU_ITEM = m.SK_MENU_ITEM
       AND m.IS_CURRENT = TRUE;

DROP TABLE DW.DT_ORDER_ANALYTICS;
       
SELECT * FROM SEMANTIC.DT_ORDER_ANALYTICS;

CREATE OR REPLACE VIEW SEMANTIC.V_EXEC_SUMMARY AS
SELECT
  DATE_VALUE,
  REGION,
  RESTAURANT_NAME,
  SUM(NET_AMOUNT) AS REVENUE,
  COUNT(DISTINCT ORDER_ID) AS ORDERS,
  DIV0(SUM(NET_AMOUNT), COUNT(DISTINCT ORDER_ID)) AS AOV
FROM SEMANTIC.DT_ORDER_ANALYTICS
GROUP BY 1,2,3;

CREATE OR REPLACE VIEW SEMANTIC.V_MENU_PERFORMANCE AS
SELECT
  DATE_VALUE,
  CUISINE,
  ITEM_NAME,
  SUM(QTY) AS QTY_SOLD,
  SUM(NET_AMOUNT) AS REVENUE
FROM SEMANTIC.DT_ORDER_ANALYTICS
GROUP BY 1,2,3;

CREATE OR REPLACE VIEW SEMANTIC.V_RESTAURANT_PERFORMANCE AS
SELECT
  DATE_VALUE,
  REGION,
  RESTAURANT_NAME,
  SUM(NET_AMOUNT) AS REVENUE,
  COUNT(DISTINCT ORDER_ID) AS ORDERS
FROM SEMANTIC.DT_ORDER_ANALYTICS
GROUP BY 1,2,3;


      
 