USE RESTAURANT_ANALYTICS_DB;
USE SCHEMA RAW;


CREATE OR REPLACE PIPE RAW.PIPE_CUSTOMERS
AUTO_INGEST = TRUE
AS
COPY INTO RAW.RAW_CUSTOMERS
FROM (
    SELECT
        $1  AS CUSTOMER_ID,
        $2  AS FIRST_NAME,
        $3  AS LAST_NAME,
        $4  AS EMAIL,
        $5  AS PHONE,
        $6  AS LOYALTY_TIER,
        $7  AS CITY,
        $8  AS STATE,
        $9  AS COUNTRY,
        $10 AS UPDATED_AT,
        CURRENT_TIMESTAMP AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @RAW.STG_RESTAURANT_S3/customers/
)
ON_ERROR = CONTINUE;




CREATE OR REPLACE PIPE RAW.PIPE_RESTAURANTS
AUTO_INGEST = TRUE
AS
COPY INTO RAW.RAW_RESTAURANTS
FROM (
    SELECT
        $1 AS RESTAURANT_ID,
        $2 AS NAME,
        $3 AS REGION,
        $4 AS CITY,
        $5 AS STATE,
        $6 AS COUNTRY,
        $7 AS OPEN_DATE,
        $8 AS SERVICE_MODES,
        $9 AS STATUS,
        CURRENT_TIMESTAMP AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @RAW.STG_RESTAURANT_S3/restaurants/
)
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE RAW.PIPE_MENU_ITEMS
AUTO_INGEST = TRUE
AS
COPY INTO RAW.RAW_MENU_ITEMS
FROM (
    SELECT
        $1 AS MENU_ITEM_ID,
        $2 AS ITEM_NAME,
        $3 AS TYPE,
        $4 AS CUISINE,
        $5 AS DIET_TYPE,
        $6 AS LIST_PRICE,
        $7 AS STATUS,
        $8 AS UPDATED_AT,
        CURRENT_TIMESTAMP AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @RAW.STG_RESTAURANT_S3/menu_items/
)
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE RAW.PIPE_ORDERS
AUTO_INGEST = TRUE
AS
COPY INTO RAW.RAW_ORDERS
FROM (
    SELECT
        $1  AS ORDER_ID,
        $2  AS ORDER_LINE_ID,
        $3  AS ORDER_DATE,
        $4  AS CUSTOMER_ID,
        $5  AS MENU_ITEM_ID,
        $6  AS RESTAURANT_ID,
        $7  AS ORDER_CHANNEL,
        $8  AS QTY,
        $9  AS UNIT_PRICE,
        $10 AS DISCOUNT_PCT,
        $11 AS PAYMENT_TYPE,
        $12 AS ORDER_STATUS,
        CURRENT_TIMESTAMP AS LOAD_TS,
        METADATA$FILENAME AS SOURCE_FILE
    FROM @RAW.STG_RESTAURANT_S3/orders/
)
ON_ERROR = CONTINUE;


SHOW PIPES;

ALTER PIPE RAW.PIPE_CUSTOMERS REFRESH;
ALTER PIPE RAW.PIPE_RESTAURANTS REFRESH;
ALTER PIPE RAW.PIPE_MENU_ITEMS REFRESH;
ALTER PIPE RAW.PIPE_ORDERS REFRESH;

ALTER PIPE RAW.PIPE_CUSTOMERS
SET PIPE_EXECUTION_PAUSED = TRUE;

ALTER PIPE RAW.PIPE_RESTAURANTS
SET PIPE_EXECUTION_PAUSED = TRUE;

ALTER PIPE RAW.PIPE_MENU_ITEMS
SET PIPE_EXECUTION_PAUSED = TRUE;

ALTER PIPE RAW.PIPE_ORDERS
SET PIPE_EXECUTION_PAUSED = TRUE;



SELECT * FROM RAW.RAW_CUSTOMERS;
SELECT * FROM RAW.RAW_RESTAURANTS;
SELECT * FROM RAW.RAW_MENU_ITEMS;

SELECT * FROM RAW.RAW_ORDERS;

SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW.RAW_CUSTOMERS',
    START_TIME => DATEADD(HOUR,-2,CURRENT_TIMESTAMP)
  )
);

TRUNCATE TABLE RAW.RAW_CUSTOMERS;
TRUNCATE TABLE RAW.RAW_RESTAURANTS;
TRUNCATE TABLE RAW.RAW_MENU_ITEMS;
TRUNCATE TABLE RAW.RAW_ORDERS;



