USE RESTAURANT_ANALYTICS_DB;
USE SCHEMA RAW;
-- RAW CUSTOMERS
CREATE OR REPLACE TABLE RAW.RAW_CUSTOMERS (
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    LOYALTY_TIER STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    UPDATED_AT STRING,

    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);



-- RAW RESTAURANTS
CREATE OR REPLACE TABLE RAW.RAW_RESTAURANTS (
    RESTAURANT_ID STRING,
    NAME STRING,
    REGION STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    OPEN_DATE STRING,
    SERVICE_MODES STRING,
    STATUS STRING,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);



-- RAW MENU ITEMS
CREATE OR REPLACE TABLE RAW.RAW_MENU_ITEMS (
    MENU_ITEM_ID STRING,
    ITEM_NAME STRING,
    TYPE STRING,
    CUISINE STRING,
    DIET_TYPE STRING,
    LIST_PRICE STRING,
    STATUS STRING,
    UPDATED_AT STRING,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);

SELECT * FROM RAW.RAW_MENU_ITEMS;



-- RAW ORDERS
CREATE OR REPLACE TABLE RAW.RAW_ORDERS (
    ORDER_ID STRING,
    ORDER_LINE_ID STRING,
    ORDER_DATE STRING,
    CUSTOMER_ID STRING,
    MENU_ITEM_ID STRING,
    RESTAURANT_ID STRING,
    ORDER_CHANNEL STRING,
    QTY STRING,
    UNIT_PRICE STRING,
    DISCOUNT_PCT STRING,
    PAYMENT_TYPE STRING,
    ORDER_STATUS STRING,
    LOAD_TS TIMESTAMP,
    SOURCE_FILE STRING
);


SELECT * FROM RAW.RAW_ORDERS;


