-- ROLES (from HLD)
CREATE ROLE IF NOT EXISTS ROLE_ADMIN;
CREATE ROLE IF NOT EXISTS ROLE_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_ETL;
CREATE ROLE IF NOT EXISTS ROLE_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_APP_STREAMLIT;

-- Simple hierarchy: ROLE_ADMIN is parent of all
GRANT ROLE ROLE_INGEST        TO ROLE ROLE_ADMIN;
GRANT ROLE ROLE_ETL           TO ROLE ROLE_ADMIN;
GRANT ROLE ROLE_ANALYST       TO ROLE ROLE_ADMIN;
GRANT ROLE ROLE_APP_STREAMLIT TO ROLE ROLE_ADMIN;

-- Warehouse usage (single WH)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_INGEST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_ETL;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_APP_STREAMLIT;

-- Database usage
GRANT USAGE ON DATABASE RESTAURANT_ANALYTICS_DB TO ROLE ROLE_ADMIN;
GRANT USAGE ON DATABASE RESTAURANT_ANALYTICS_DB TO ROLE ROLE_INGEST;
GRANT USAGE ON DATABASE RESTAURANT_ANALYTICS_DB TO ROLE ROLE_ETL;
GRANT USAGE ON DATABASE RESTAURANT_ANALYTICS_DB TO ROLE ROLE_ANALYST;
GRANT USAGE ON DATABASE RESTAURANT_ANALYTICS_DB TO ROLE ROLE_APP_STREAMLIT;

-- Schema usage (RAW, CLEANED, DW, SEMANTIC)
GRANT USAGE ON SCHEMA RESTAURANT_ANALYTICS_DB.RAW      TO ROLE ROLE_INGEST;
GRANT USAGE ON SCHEMA RESTAURANT_ANALYTICS_DB.CLEANED  TO ROLE ROLE_ETL;
GRANT USAGE ON SCHEMA RESTAURANT_ANALYTICS_DB.DW       TO ROLE ROLE_ETL;
GRANT USAGE ON SCHEMA RESTAURANT_ANALYTICS_DB.DW       TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA RESTAURANT_ANALYTICS_DB.SEMANTIC TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA RESTAURANT_ANALYTICS_DB.SEMANTIC TO ROLE ROLE_APP_STREAMLIT;

-- (Optional) Admin needs broad visibility over OPS/metadata if you add it later
-- GRANT USAGE ON SCHEMA RESTAURANT_ANALYTICS_DB.OPS TO ROLE ROLE_ADMIN;

-- INGEST: write to RAW (tables/stages/pipes if applicable)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.RAW TO ROLE ROLE_INGEST;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.RAW TO ROLE ROLE_INGEST;

-- If you use stages/pipes in RAW:
-- GRANT USAGE, READ, WRITE ON ALL STAGES  IN SCHEMA RESTAURANT_ANALYTICS_DB.RAW TO ROLE ROLE_INGEST;
-- GRANT USAGE, READ, WRITE ON FUTURE STAGES IN SCHEMA RESTAURANT_ANALYTICS_DB.RAW TO ROLE ROLE_INGEST;
-- GRANT USAGE ON ALL PIPES IN SCHEMA RESTAURANT_ANALYTICS_DB.RAW TO ROLE ROLE_INGEST;
-- GRANT USAGE ON FUTURE PIPES IN SCHEMA RESTAURANT_ANALYTICS_DB.RAW TO ROLE ROLE_INGEST;

-- ETL: read RAW & CLEANED, write CLEANED & DW (adjust as needed)
GRANT SELECT ON ALL TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.RAW     TO ROLE ROLE_ETL;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.RAW  TO ROLE ROLE_ETL;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.CLEANED TO ROLE ROLE_ETL;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.CLEANED TO ROLE ROLE_ETL;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.DW TO ROLE ROLE_ETL;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.DW TO ROLE ROLE_ETL;

-- ANALYST: read DW and SEMANTIC (views/tables) – no write
GRANT SELECT ON ALL TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.DW        TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RESTAURANT_ANALYTICS_DB.DW     TO ROLE ROLE_ANALYST;

GRANT SELECT ON ALL VIEWS  IN SCHEMA RESTAURANT_ANALYTICS_DB.SEMANTIC  TO ROLE ROLE_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RESTAURANT_ANALYTICS_DB.SEMANTIC TO ROLE ROLE_ANALYST;

-- APP (Streamlit): read SEMANTIC only (governed read)
GRANT SELECT ON ALL VIEWS  IN SCHEMA RESTAURANT_ANALYTICS_DB.SEMANTIC  TO ROLE ROLE_APP_STREAMLIT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RESTAURANT_ANALYTICS_DB.SEMANTIC TO ROLE ROLE_APP_STREAMLIT;