USE RESTAURANT_ANALYTICS_DB;
USE SCHEMA RAW;


CREATE OR REPLACE STORAGE INTEGRATION S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::498504718091:role/ankit-snowflake'
  STORAGE_ALLOWED_LOCATIONS = ('s3://ankit-snowflake/');

DESC INTEGRATION S3_INT;


CREATE OR REPLACE STAGE RAW.STG_RESTAURANT_S3
URL='s3://ankit-snowflake/landing/restaurant_analytics/'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT=RAW.FF_CSV;

LIST @RAW.STG_RESTAURANT_S3;

